import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'english' | 'kannada';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string; // Translation function
}

const defaultContextValue: LanguageContextType = {
  language: 'english',
  setLanguage: () => {},
  t: (key: string) => key,
};

const LanguageContext = createContext<LanguageContextType>(defaultContextValue);

// Translations dictionary
const translations: Record<Language, Record<string, string>> = {
  english: {
    // Navigation
    'nav.home': 'Home',
    'nav.sahayak': 'Namma Sahayak',
    'nav.vidhana': 'Namma Vidhana',
    'nav.contact': 'Contact',
    'nav.slogan': 'Legal Assistance Simplified',
    'nav.logo': 'NammaKendra',
    
    // Hero Section
    'hero.title': 'Legal Help Made Simple',
    'hero.subtitle': 'Access legal information in a way you can understand',
    'hero.getStarted': 'Get Started',
    'hero.learnMore': 'Learn More',
    'hero.name': 'NammaKendra',
    'hero.tagline': 'Legal Assistance Simplified - Your resource for legal knowledge',
    'hero.mission': 'Our mission is to make legal knowledge accessible to all through AI-powered tools and easy-to-understand content.',
    
    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'We provide tools to help you navigate complex legal matters with ease and confidence.',
    'services.sahayak.title': 'Namma Sahayak',
    'services.sahayak.description': 'Our AI-powered chatbot that answers your legal questions in simple language and helps guide you through common legal procedures.',
    'services.sahayak.feature1': '✔️24/7 answers to legal questions',
    'services.sahayak.feature2': '✔️Simple explanations of complex terms',
    'services.sahayak.feature3': '✔️Step-by-step guidance for procedures',
    'services.sahayak.button': 'Chat with Sahayak',
    'services.vidhana.title': 'Namma Vidhana',
    'services.vidhana.description': 'Upload legal documents to scan, simplify, and explain them in everyday language.',
    'services.vidhana.feature1': '✔️Scan and analyze legal documents',
    'services.vidhana.feature2': '✔️Get simplified summaries',
    'services.vidhana.feature3': '✔️Highlight important sections and deadlines',
    'services.vidhana.button': 'Upload Document',
    
    // How It Works Section
    'how.title': 'How It Works',
    'how.subtitle': 'Simple steps to get the legal help you need',
    'how.step1.title': 'Choose a Service',
    'how.step1.description': 'Select either NammaSahayak for questions or NammaVidhana for document assistance.',
    'how.step2.title': 'Provide Information',
    'how.step2.description': 'Ask your question or upload your document that needs explanation.',
    'how.step3.title': 'Get Simple Answers',
    'how.step3.description': 'Receive easy-to-understand explanations and guidance for your legal needs.',
    
    // Testimonials Section
    'testimonials.title': 'What Our Users Say',
    'testimonials.subtitle': 'Real experiences from people we\'ve helped',
    'testimonials.1.name': 'Ramesh K.',
    'testimonials.1.title': 'Retired Teacher',
    'testimonials.1.content': 'NammaSahayak helped me understand my pension rights in simple language. The chatbot explained everything step by step, and I didn\'t feel overwhelmed by legal jargon.',
    'testimonials.2.name': 'Lakshmi M.',
    'testimonials.2.title': 'Homemaker',
    'testimonials.2.content': 'The document scanner was so helpful when I received a complex property notice. It highlighted important dates and explained what actions I needed to take in simple language.',
    'testimonials.3.name': 'Venkat R.',
    'testimonials.3.title': 'Senior Citizen',
    'testimonials.3.content': 'My grandson suggested I try this service when I was confused about healthcare benefits. The large text option and simple explanations made it easy for me to navigate and get answers.',
    
    // CTA Section
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Access the legal help you need in language you can understand.',
    'cta.chatButton': 'Chat with NammaSahayak',
    'cta.uploadButton': 'Upload a Document',
    
    // Chat interface
    'chat.title': 'NammaSahayak Chat',
    'chat.subtitle': 'Ask me any legal questions you have',
    'chat.placeholder': 'Type your legal question...',
    'chat.send': 'Send message',
    'chat.startRecording': 'Start recording',
    'chat.stopRecording': 'Stop recording',
    'chat.welcome': 'Hello! I\'m NammaSahayak, your legal assistant. How can I help you today?',
    'chat.error': 'Failed to get a response. Please try again.',
    'chat.speechError': 'Failed to recognize speech. Please try again.',
    'chat.speechNotSupported': 'Your browser doesn\'t support speech recognition.',
    
    // Document upload
    'document.title': 'Upload Legal Document',
    'document.description': 'Upload your legal document to get a simplified explanation. We support PDF, DOCX, and TXT files up to 10MB.',
    'document.drag': 'Drag and drop your document here',
    'document.browse': 'or click to browse files (PDF, DOCX, TXT up to 10MB)',
    'document.browseButton': 'Browse Files',
    'document.remove': 'Remove',
    'document.analyze': 'Analyze Document',
    'document.processing': 'Processing...',
    'document.howItWorks': 'How It Works',
    'document.step1': 'Upload your legal document (court order, contract, etc.)',
    'document.step2': 'Our AI will analyze the document',
    'document.step3': 'Get a simplified explanation with highlighted key points',
    'document.step4': 'See deadlines, requirements, and actions needed',
    
    // Page titles
    'page.vidhana.title': 'NammaVidhana Document Simplifier',
    'page.vidhana.description': 'Upload legal documents and get them explained in simple, easy-to-understand language. Our AI helps you make sense of complex legal jargon.',
    'page.vidhana.service': 'Document Simplification Service',
    'page.vidhana.serviceDesc': 'Our tool analyzes legal documents and translates them into plain language that\'s easy to understand. You\'ll get:',
    'page.vidhana.feature1': 'A simplified summary of the entire document',
    'page.vidhana.feature2': 'Highlighted key points and important information',
    'page.vidhana.feature3': 'Clear explanation of legal terms used',
    'page.vidhana.feature4': 'Important dates, deadlines, and required actions',
    'page.vidhana.benefit': 'This service helps you understand legal documents without needing to hire an expensive lawyer for basic explanations.',
    'page.vidhana.documentTypes': 'Documents You Can Upload',
    'page.vidhana.docType1': 'Court Notices and Orders',
    'page.vidhana.docType2': 'Legal Contracts and Agreements',
    'page.vidhana.docType3': 'Government Notices',
    'page.vidhana.docType4': 'Property Documents',
    
    // NammaSahayak Page
    'sahayak.title': 'Namma Sahayak',
    'sahayak.subtitle': 'Get answers to legal questions in simple language',
    'sahayak.description': 'Namma Sahayak is an AI-powered chatbot that provides information related to legal rights, procedures, and answers to your legal questions. Type your question or use your microphone to speak.',
    'sahayak.features.title': 'Features of this service',
    'sahayak.feature1.title': 'Simple Explanations',
    'sahayak.feature1.description': 'We translate legal terminology into language you can easily understand.',
    'sahayak.feature2.title': 'Voice Input',
    'sahayak.feature2.description': 'No need to type - just speak and ask your question.',
    'sahayak.feature3.title': '24/7 Availability',
    'sahayak.feature3.description': 'Get help with your legal questions any time.',
    'sahayak.commonTopics': 'Common Topics',
    'sahayak.topic1': 'Property rights and disputes',
    'sahayak.topic2': 'Pension and social security benefits',
    'sahayak.topic3': 'Family law and inheritance',
    'sahayak.topic4': 'Consumer rights',
    'sahayak.tip': 'Tip: Try to ask your question as specifically as possible so we can give you a more helpful answer.',
    
    // NammaVidhana Page
    'vidhana.title': 'Namma Vidhana Document Simplifier',
    'vidhana.description': 'Upload legal documents and get them explained in simple, easy-to-understand language. Our AI helps you make sense of complex legal jargon.',
    'vidhana.service': 'Document Simplification Service',
    'vidhana.serviceDesc': 'Our tool analyzes legal documents and translates them into plain language that\'s easy to understand. You\'ll get:',
    'vidhana.feature1': 'A simplified summary of the entire document',
    'vidhana.feature2': 'Highlighted key points and important information',
    'vidhana.feature3': 'Clear explanation of legal terms used',
    'vidhana.feature4': 'Important dates, deadlines, and required actions',
    'vidhana.benefit': 'This service helps you understand legal documents without needing to hire an expensive lawyer for basic explanations.',
    'vidhana.documentTypes': 'Documents You Can Upload',
    'vidhana.docType1': 'Court Notices and Orders',
    'vidhana.docType2': 'Legal Contracts and Agreements',
    'vidhana.docType3': 'Government Notices',
    'vidhana.docType4': 'Property Documents',
    
    // About Page
    'about.title': 'About Us',
    'about.nammaKendra': 'About NammaKendra',
    'about.mission': 'Our Mission',
    'about.mission.text1': 'NammaKendra was established with a simple yet powerful mission: to make legal information accessible to all citizens, especially the elderly and underprivileged who typically struggle to navigate complex legal documents and procedures.',
    'about.mission.text2': 'Our motto "Government at your home" reflects our commitment to bringing legal assistance and government services to citizens in a way that is easy to understand and take action on.',
    'about.services': 'Our Services',
    'about.sahayak.title': 'NammaSahayak (Our Helper)',
    'about.sahayak.description': 'An AI-powered assistant that can answer questions about legal rights, government schemes, and procedures in simple, everyday language.',
    'about.vidhana.title': 'NammaVidhana (Our System)',
    'about.vidhana.description': 'A document simplification tool that breaks down complex legal documents into clear, understandable language with highlighted key points.',
    'about.team': 'Our Team',
    'about.team.text1': 'NammaKendra was founded by a team of legal experts, technologists, and social advocates who share the common goal of democratizing legal information. Our diverse team combines expertise in law, artificial intelligence, user experience design, and community outreach.',
    'about.team.text2': 'We actively collaborate with government departments, legal aid organizations, and community groups to ensure our services are relevant, accurate, and truly beneficial to those who need them most.',
    'about.commitment': 'Our Commitment',
    'about.commitment.text1': 'We are committed to removing barriers to legal information through technology, simple language, and inclusive design. We believe that understanding your rights and obligations is fundamental to full citizenship, and we strive to make this possible for everyone regardless of education, background, or technical proficiency.',
    'about.commitment.text2': 'NammaKendra is dedicated to continuous improvement, responding to community needs, and expanding our services to reach more citizens across different regions and languages.',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions or need assistance? We\'re here to help. Fill out the form below or use the alternative contact methods.',
    'contact.phone': 'Phone',
    'contact.phone.availability': 'Available Monday to Friday, 9 AM to 5 PM',
    'contact.email': 'Email',
    'contact.email.response': 'We respond within 24 hours',
    'contact.address': 'Address',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number (Optional)',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Your message has been sent successfully!',
    'contact.form.error': 'An error occurred while sending your message. Please try again.',
    'contact.form.nameRequired': 'Name is required',
    'contact.form.emailRequired': 'Email is required',
    'contact.form.emailInvalid': 'Please provide a valid email address',
    'contact.form.subjectRequired': 'Subject is required',
    'contact.form.messageRequired': 'Message is required',
    'contact.form.messageTooShort': 'Message must be at least 10 characters',
    
    // Accessibility Page
    'accessibility.title': 'Accessibility',
    'accessibility.lastUpdated': 'Last Updated: April 20, 2023',
    'accessibility.commitment.title': 'Our Commitment to Accessibility',
    'accessibility.commitment.text1': 'At NammaKendra, we are committed to ensuring our digital services are accessible to all users, including those with disabilities. We believe that everyone should have equal access to legal information and assistance, regardless of their abilities or the technologies they use.',
    'accessibility.commitment.text2': 'We strive to meet the Web Content Accessibility Guidelines (WCAG) 2.1 at Level AA and continue to improve our platform with regular accessibility reviews and updates.',
    'accessibility.features.title': 'Accessibility Features',
    'accessibility.features.intro': 'Our website includes the following accessibility features:',
    'accessibility.features.fontSizeControl': 'Adjustable font size controls that allow users to increase or decrease text size for better readability',
    'accessibility.features.clearDesign': 'Clear, consistent layout and navigation across the website',
    'accessibility.features.highContrast': 'High contrast color schemes and readable text',
    'accessibility.features.textToSpeech': 'Voice input and text-to-speech compatibility for our chat interface',
    'accessibility.features.keyboardNav': 'Keyboard accessibility for all website functions',
    'accessibility.features.screenReader': 'Screen reader compatibility with appropriate alt text for images and ARIA landmarks',
    'accessibility.features.simpleLanguage': 'Simple, clear language in all our content and legal explanations',
    'accessibility.conformance.title': 'Conformance Status',
    'accessibility.conformance.text1': 'We aim to conform to WCAG 2.1 Level AA standards. While we make every effort to ensure accessibility, we recognize that there may be areas for improvement.',
    'accessibility.conformance.text2': 'Our website undergoes regular testing with various assistive technologies to identify and address accessibility issues.',
    'accessibility.howToUse.title': 'How to Use Accessibility Features',
    'accessibility.howToUse.fontSizeTitle': 'Font Size Adjustment',
    'accessibility.howToUse.fontSizeText': 'You can adjust the text size on our website using the font size controls in the header. Click the "A+" button to increase the font size or "A-" to decrease it.',
    'accessibility.howToUse.clearDesignTitle': 'Navigation and Layout',
    'accessibility.howToUse.clearDesignText': 'Our website is designed with a clear, logical structure to help you find information easily. The main navigation menu is consistently placed at the top of each page.',
    'accessibility.howToUse.keyboardNavTitle': 'Keyboard Navigation',
    'accessibility.howToUse.keyboardNavText': 'All functions on our website can be accessed using a keyboard. Use the Tab key to navigate through links and interactive elements, and Enter to activate them.',
    'accessibility.limitations.title': 'Known Limitations',
    'accessibility.limitations.intro': 'We are continuously working to improve our website\'s accessibility, but there may be some current limitations:',
    'accessibility.limitations.item1': 'Some document formats uploaded by users may not be fully accessible',
    'accessibility.limitations.item2': 'Certain complex legal terms may be challenging to simplify while maintaining accuracy',
    'accessibility.feedback.title': 'Feedback and Assistance',
    'accessibility.feedback.text': 'We welcome your feedback on the accessibility of the NammaKendra website.',
    'accessibility.feedback.item1': 'If you encounter any barriers or have suggestions for improvement, please contact us through our Contact page or email us directly at accessibility@nammasahayak.org',
    'accessibility.feedback.item2': 'If you need assistance accessing any part of our website or services, our support team is ready to help. We can provide information in alternative formats upon request',
    'accessibility.feedback.item3': 'Your feedback helps us continuously improve our accessibility features and ensure our services are usable by everyone',
    
    // Terms of Service Page
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last Updated: April 15, 2023',
    'terms.section1.title': 'Introduction and Acceptance',
    'terms.section1.text': 'Welcome to NammaKendra. By using our website and services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.',
    'terms.section2.title': 'Description of Services',
    'terms.section2.text1': 'NammaKendra provides AI-powered legal assistance tools designed to help users understand legal documents and get answers to legal questions in simple language. Our services include document simplification and an AI chatbot for legal queries.',
    'terms.section2.text2': 'While we strive to provide accurate and helpful information, our services are meant for informational purposes only and should not be considered as legal advice. We recommend consulting with a qualified legal professional for specific legal issues.',
    'terms.section3.title': 'User Responsibilities',
    'terms.section3.text1': 'When using our services, you agree to provide accurate information and to use the platform in a lawful manner. You are responsible for maintaining the confidentiality of any account information and for all activities that occur under your account.',
    'terms.section3.text2': 'You agree not to use our services for any illegal purpose or in any way that could damage, disable, or impair our services. You also agree not to attempt to gain unauthorized access to any part of our services.',
    'terms.section4.title': 'Intellectual Property',
    'terms.section4.text': 'The content, organization, graphics, design, and other matters related to NammaKendra are protected under applicable copyrights and other proprietary laws. The copying, redistribution, or publication of any part of our website is prohibited without express written consent.',
    'terms.section5.title': 'Limitation of Liability',
    'terms.section5.text1': 'NammaKendra and its employees, agents, and affiliates will not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages resulting from your use of or inability to use our services.',
    'terms.section5.text2': 'The information provided on our website is for general informational purposes only. It is not intended as legal advice and should not be relied upon as such.',
    'terms.section6.title': 'Privacy Policy',
    'terms.section6.text1': 'Your use of NammaKendra is also governed by our Privacy Policy, which can be found on our website.',
    'terms.section6.text2': 'Please review this policy to understand how we collect, use, and protect your information.',
    'terms.section7.title': 'Modifications to Terms',
    'terms.section7.text': 'We reserve the right to modify these terms at any time. We will provide notice of significant changes by posting a notice on our homepage. Your continued use of our services after such changes constitutes your acceptance of the new terms.',
    'terms.section8.title': 'Governing Law',
    'terms.section8.text1': 'These terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions.',
    'terms.section8.text2': 'Any legal action or proceeding arising out of these Terms or your access to or use of the Service shall be instituted exclusively in the courts located in Bangalore, Karnataka, India.',
    'terms.section9.title': 'Contact Information',
    'terms.section9.text': 'If you have any questions about these Terms of Service, please contact us at legal@nammasahayak.org.',
    
    // Privacy Policy Page
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated: April 15, 2023',
    'privacy.intro.title': 'Introduction',
    'privacy.intro.text': 'At NammaKendra, we value your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our services. Please read this policy carefully to understand our practices regarding your personal data.',
    'privacy.collect.title': 'Information We Collect',
    'privacy.collect.text': 'We may collect several types of information from and about users of our website, including:',
    'privacy.collect.identity': 'Identity Information: Names and basic demographic information when provided voluntarily',
    'privacy.collect.contact': 'Contact Information: Email addresses, phone numbers, and other contact details you provide',
    'privacy.collect.technical': 'Technical Information: IP addresses, browser types, device information, and cookies',
    'privacy.collect.usage': 'Usage Data: Information about how you interact with our website and services',
    'privacy.collect.content': 'Content Data: Documents you upload and questions you submit to our platform',
    'privacy.use.title': 'How We Use Your Information',
    'privacy.use.text': 'We use the information we collect about you for various purposes, including:',
    'privacy.use.item1': 'To provide and maintain our services, including processing documents and answering legal questions',
    'privacy.use.item2': 'To improve our website and services based on the information and feedback we receive from you',
    'privacy.use.item3': 'To personalize your experience and deliver content most relevant to you',
    'privacy.use.item4': 'To communicate with you about updates, support, and administrative messages',
    'privacy.use.item5': 'To analyze usage patterns and improve our website functionality',
    'privacy.security.title': 'Data Security',
    'privacy.security.text': 'We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, please be aware that no method of transmission over the Internet or method of electronic storage is 100% secure.',
    'privacy.rights.title': 'Your Data Protection Rights',
    'privacy.rights.text': 'Depending on your location and applicable laws, you may have the following rights regarding your personal data:',
    'privacy.rights.item1': 'Right to access the personal information we hold about you',
    'privacy.rights.item2': 'Right to rectification of inaccurate personal information',
    'privacy.rights.item3': 'Right to erasure of your personal information',
    'privacy.rights.item4': 'Right to restrict or object to processing of your personal information',
    'privacy.rights.item5': 'Right to data portability (receiving a copy of your personal data)',
    'privacy.rights.item6': 'Right to withdraw consent at any time',
    'privacy.rights.item7': 'Right to lodge a complaint with a supervisory authority',
    'privacy.cookies.title': 'Cookies and Tracking Technologies',
    'privacy.cookies.text1': 'We use cookies and similar tracking technologies to track activity on our website and store certain information. Cookies are files with small amount of data that may include an anonymous unique identifier.',
    'privacy.cookies.text2': 'You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our site.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.text': 'If you have any questions about this Privacy Policy, please contact us at privacy@nammasahayak.org.',
    
    // Additional privacy items from the page
    'privacy.share.title': 'Information Sharing and Disclosure',
    'privacy.share.text': 'We do not sell or rent your personal information to third parties. We may disclose your personal information in the following situations:',
    'privacy.share.item1': 'To comply with legal obligations',
    'privacy.share.item2': 'To protect and defend our rights or property',
    'privacy.share.item3': 'With service providers who perform services on our behalf',
    'privacy.share.item4': 'With your consent or at your direction',
    'privacy.children.title': 'Children\'s Privacy',
    'privacy.children.text': 'Our services are not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If we learn we have collected personal information from a child under 13, we will delete that information as quickly as possible.',
    'privacy.changes.title': 'Changes to This Privacy Policy',
    'privacy.changes.text': 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.',
    'privacy.howToUse.title': 'How to Exercise Your Rights',
    'privacy.howToUse.text': 'To exercise any of your data protection rights, please contact us using the information provided in the Contact Us section.',
    'privacy.conformance.title': 'Regulatory Compliance',
    'privacy.conformance.text1': 'We comply with applicable data protection laws, including the General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA) where applicable.',
    'privacy.conformance.text2': 'We make every effort to handle your personal information responsibly and in accordance with these regulations.',
    'privacy.limitations.title': 'Limitations',
    'privacy.limitations.intro': 'While we strive to protect your privacy, there are some limitations:',
    'privacy.limitations.item1': 'Third-party services used on our platform may have their own privacy policies',
    'privacy.limitations.item2': 'We may be required to disclose information in response to lawful requests by public authorities',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.contact': 'Contact Us',
    'footer.address': '123 Main Street, Bangalore, Karnataka',
    'footer.phone': '+91 123 456 7890',
    'footer.email': 'info@nammasahayak.org',
    'footer.copyright': 'All rights reserved.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.accessibility': 'Accessibility',
    'footer.slogan': 'Making legal knowledge accessible to all',
    
    // Language selector
    'language.english': 'English',
    'language.kannada': 'ಕನ್ನಡ',
  },
  
  kannada: {
    // Navigation
    'nav.home': 'ಮುಖಪುಟ',
    'nav.sahayak': 'ನಮ್ಮ ಸಹಾಯಕ',
    'nav.vidhana': 'ನಮ್ಮ ವಿಧಾನ',
    'nav.contact': 'ಸಂಪರ್ಕ',
    'nav.slogan': 'ಕಾನೂನು ಸಹಾಯ ಸರಳೀಕರಿಸಲಾಗಿದೆ',
    'nav.logo': 'ನಮ್ಮಕೇಂದ್ರ',
    
    // About Us Page
    'about.title': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'about.nammaKendra': 'ನಮ್ಮಕೇಂದ್ರದ ಬಗ್ಗೆ',
    'about.mission': 'ನಮ್ಮ ಉದ್ದೇಶ',
    'about.mission.text1': 'ನಮ್ಮಕೇಂದ್ರ ಸರಳವಾದರೂ ಶಕ್ತಿಯುತವಾದ ಉದ್ದೇಶದೊಂದಿಗೆ ಸ್ಥಾಪಿಸಲಾಗಿದೆ: ಕಾನೂನು ಮಾಹಿತಿಯನ್ನು ಎಲ್ಲರಿಗೂ ಲಭ್ಯವಾಗುವಂತೆ ಮಾಡುವುದು, ವಿಶೇಷವಾಗಿ ಹಿರಿಯ ಮತ್ತು ಅನುಕೂಲವಿಲ್ಲದ ನಾಗರಿಕರಿಗೆ ಸಂಕೀರ್ಣ ಕಾನೂನು ದಾಖಲೆಗಳು ಮತ್ತು ಪ್ರಕ್ರಿಯೆಗಳನ್ನು ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲು ಸಾಧಾರಣವಾಗಿ ಕಷ್ಟಪಡುತ್ತಿದ್ದಾರೆ.',
    'about.mission.text2': 'ನಮ್ಮ ಧ್ಯೇಯವಾಕ್ಯ "ನಿಮ್ಮ ಮನೆಯಲ್ಲಿ ಸರ್ಕಾರ" ಕಾನೂನು ಸಹಾಯ ಮತ್ತು ಸರ್ಕಾರೀ ಸೇವೆಗಳನ್ನು ನಾಗರಿಕರಿಗೆ ನೇರವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಮತ್ತು ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳಲು ಸುಲಭವಾದ ರೀತಿಯಲ್ಲಿ ತರುವ ನಮ್ಮ ಬದ್ಧತೆಯನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ.',
    'about.services': 'ನಮ್ಮ ಸೇವೆಗಳು',
    'about.sahayak.title': 'ನಮ್ಮಸಹಾಯಕ (ನಮ್ಮ ಸಹಾಯಕ)',
    'about.sahayak.description': 'ಕಾನೂನು ಹಕ್ಕುಗಳು, ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು ಮತ್ತು ಕಾರ್ಯವಿಧಾನಗಳ ಬಗ್ಗೆ ಪ್ರಶ್ನೆಗಳಿಗೆ ಸರಳ, ದೈನಂದಿನ ಭಾಷೆಯಲ್ಲಿ ಉತ್ತರಿಸಬಲ್ಲ AI-ಪವರ್ಡ್ ಸಹಾಯಕ.',
    'about.vidhana.title': 'ನಮ್ಮವಿಧಾನ (ನಮ್ಮ ವ್ಯವಸ್ಥೆ)',
    'about.vidhana.description': 'ಸಂಕೀರ್ಣ ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಪ್ರಮುಖ ಅಂಶಗಳೊಂದಿಗೆ ಸ್ಪಷ್ಟ, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದಾದ ಭಾಷೆಯಲ್ಲಿ ವಿಭಜಿಸುವ ದಾಖಲೆ ಸರಳೀಕರಣ ಉಪಕರಣ.',
    'about.team': 'ನಮ್ಮ ತಂಡ',
    'about.team.text1': 'ನಮ್ಮಕೇಂದ್ರವನ್ನು ಕಾನೂನು ಮಾಹಿತಿಯನ್ನು ಪ್ರಜಾಪ್ರಭುತ್ವಗೊಳಿಸುವ ಸಾಮಾನ್ಯ ಗುರಿಯನ್ನು ಹಂಚಿಕೊಳ್ಳುವ ಕಾನೂನು ತಜ್ಞರು, ತಂತ್ರಜ್ಞಾನಿಗಳು ಮತ್ತು ಸಾಮಾಜಿಕ ವಕೀಲರ ತಂಡವು ಸ್ಥಾಪಿಸಿದೆ. ನಮ್ಮ ವೈವಿಧ್ಯಮಯ ತಂಡವು ಕಾನೂನು, ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ, ಬಳಕೆದಾರ ಅನುಭವ ವಿನ್ಯಾಸ ಮತ್ತು ಸಮುದಾಯ ಔಟ್‌ರೀಚ್‌ನಲ್ಲಿ ಪರಿಣಿತಿಯನ್ನು ಒಟ್ಟುಗೂಡಿಸುತ್ತದೆ.',
    'about.team.text2': 'ನಮ್ಮ ಸೇವೆಗಳು ಸಂಬಂಧಪಟ್ಟವೆ, ನಿಖರವಾಗಿವೆ ಮತ್ತು ಅವುಗಳನ್ನು ಅತ್ಯಂತ ಅಗತ್ಯವಿರುವವರಿಗೆ ನಿಜವಾಗಿಯೂ ಪ್ರಯೋಜನಕಾರಿಯಾಗಿವೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನಾವು ಸರ್ಕಾರಿ ಇಲಾಖೆಗಳು, ಕಾನೂನು ನೆರವು ಸಂಸ್ಥೆಗಳು ಮತ್ತು ಸಮುದಾಯ ಗುಂಪುಗಳೊಂದಿಗೆ ಸಕ್ರಿಯವಾಗಿ ಸಹಕರಿಸುತ್ತೇವೆ.',
    'about.commitment': 'ನಮ್ಮ ಬದ್ಧತೆ',
    'about.commitment.text1': 'ನಾವು ತಂತ್ರಜ್ಞಾನ, ಸರಳ ಭಾಷೆ ಮತ್ತು ಸಮಾವೇಶಿ ವಿನ್ಯಾಸದ ಮೂಲಕ ಕಾನೂನು ಮಾಹಿತಿಗೆ ಅಡ್ಡಿಗಳನ್ನು ತೆಗೆದುಹಾಕಲು ಬದ್ಧರಾಗಿದ್ದೇವೆ. ನಿಮ್ಮ ಹಕ್ಕುಗಳು ಮತ್ತು ಕಡ್ಡಾಯಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು ಸಂಪೂರ್ಣ ಪೌರತ್ವಕ್ಕೆ ಮೂಲಭೂತವಾಗಿದೆ ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ, ಮತ್ತು ಶಿಕ್ಷಣ, ಹಿನ್ನೆಲೆ ಅಥವಾ ತಾಂತ್ರಿಕ ಪ್ರವೀಣತೆಯನ್ನು ಲೆಕ್ಕಿಸದೆ ಎಲ್ಲರಿಗೂ ಇದನ್ನು ಸಾಧ್ಯವಾಗಿಸಲು ನಾವು ಪ್ರಯತ್ನಿಸುತ್ತೇವೆ.',
    'about.commitment.text2': 'ನಮ್ಮಕೇಂದ್ರವು ನಿರಂತರ ಸುಧಾರಣೆ, ಸಮುದಾಯದ ಅಗತ್ಯತೆಗಳಿಗೆ ಪ್ರತಿಕ್ರಿಯಿಸುವುದು ಮತ್ತು ವಿವಿಧ ಪ್ರದೇಶಗಳು ಮತ್ತು ಭಾಷೆಗಳಲ್ಲಿ ಹೆಚ್ಚಿನ ನಾಗರಿಕರನ್ನು ತಲುಪಲು ನಮ್ಮ ಸೇವೆಗಳನ್ನು ವಿಸ್ತರಿಸುವುದಕ್ಕೆ ಸಮರ್ಪಿತವಾಗಿದೆ.',
    
    // Contact Page
    'contact.title': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    'contact.subtitle': 'ಪ್ರಶ್ನೆಗಳಿದ್ದರೆ ಅಥವಾ ಸಹಾಯ ಬೇಕಾದರೆ? ನಾವು ಸಹಾಯ ಮಾಡಲು ಇಲ್ಲಿದ್ದೇವೆ. ಕೆಳಗಿನ ಫಾರ್ಮ್ ಅನ್ನು ಭರ್ತಿ ಮಾಡಿ ಅಥವಾ ಪರ್ಯಾಯ ಸಂಪರ್ಕ ವಿಧಾನಗಳನ್ನು ಬಳಸಿ.',
    'contact.phone': 'ಫೋನ್',
    'contact.phone.availability': 'ಸೋಮವಾರದಿಂದ ಶುಕ್ರವಾರದವರೆಗೆ, ಬೆಳಿಗ್ಗೆ 9 ರಿಂದ ಸಂಜೆ 5 ರವರೆಗೆ ಲಭ್ಯವಿದೆ',
    'contact.email': 'ಇಮೇಲ್',
    'contact.email.response': 'ನಾವು 24 ಗಂಟೆಗಳೊಳಗೆ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತೇವೆ',
    'contact.address': 'ವಿಳಾಸ',
    'contact.form.name': 'ಹೆಸರು',
    'contact.form.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'contact.form.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ (ಐಚ್ಛಿಕ)',
    'contact.form.subject': 'ವಿಷಯ',
    'contact.form.message': 'ಸಂದೇಶ',
    'contact.form.submit': 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    'contact.form.success': 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ!',
    'contact.form.error': 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಕಳುಹಿಸುವಾಗ ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'contact.form.nameRequired': 'ಹೆಸರು ಅಗತ್ಯವಿದೆ',
    'contact.form.emailRequired': 'ಇಮೇಲ್ ಅಗತ್ಯವಿದೆ',
    'contact.form.emailInvalid': 'ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ಒದಗಿಸಿ',
    'contact.form.subjectRequired': 'ವಿಷಯ ಅಗತ್ಯವಿದೆ',
    'contact.form.messageRequired': 'ಸಂದೇಶ ಅಗತ್ಯವಿದೆ',
    'contact.form.messageTooShort': 'ಸಂದೇಶವು ಕನಿಷ್ಠ 10 ಅಕ್ಷರಗಳನ್ನು ಹೊಂದಿರಬೇಕು',
    
    // NammaSahayak Page
    'sahayak.title': 'ನಮ್ಮ ಸಹಾಯಕ',
    'sahayak.subtitle': 'ಕಾನೂನು ಪ್ರಶ್ನೆಗಳಿಗೆ ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ',
    'sahayak.description': 'ನಮ್ಮ ಸಹಾಯಕವು ಕಾನೂನು ಹಕ್ಕುಗಳು, ಕಾರ್ಯವಿಧಾನಗಳು ಮತ್ತು ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ ಮಾಹಿತಿಯನ್ನು ನೀಡುವ AI-ಆಧಾರಿತ ಚಾಟ್‌ಬಾಟ್ ಆಗಿದೆ. ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಮೈಕ್ರೋಫೋನ್ ಬಳಸಿ ಮಾತನಾಡಿ.',
    'sahayak.features.title': 'ಈ ಸೇವೆಯ ವೈಶಿಷ್ಟ್ಯಗಳು',
    'sahayak.feature1.title': 'ಸರಳವಾದ ವಿವರಣೆಗಳು',
    'sahayak.feature1.description': 'ಕಾನೂನು ಪರಿಭಾಷೆಯನ್ನು ನೀವು ಸುಲಭವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದಾದ ಭಾಷೆಗೆ ಅನುವಾದಿಸುತ್ತೇವೆ.',
    'sahayak.feature2.title': 'ಧ್ವನಿ ಒಳಹೊಕ್ಕುವಿಕೆ',
    'sahayak.feature2.description': 'ಟೈಪ್ ಮಾಡಲು ಅಲ್ಲಿ ಬೇಡಿರಿ - ಕೇವಲ ಮಾತನಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ.',
    'sahayak.feature3.title': '24/7 ಲಭ್ಯತೆ',
    'sahayak.feature3.description': 'ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಗಳಿಗೆ ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಸಹಾಯವನ್ನು ಪಡೆಯಿರಿ.',
    'sahayak.commonTopics': 'ಸಾಮಾನ್ಯ ವಿಷಯಗಳು',
    'sahayak.topic1': 'ಆಸ್ತಿ ಹಕ್ಕುಗಳು ಮತ್ತು ವಿವಾದಗಳು',
    'sahayak.topic2': 'ಪಿಂಚಣಿ ಮತ್ತು ಸಾಮಾಜಿಕ ಭದ್ರತೆಯ ಪ್ರಯೋಜನಗಳು',
    'sahayak.topic3': 'ಕುಟುಂಬ ಕಾನೂನು ಮತ್ತು ಉತ್ತರಾಧಿಕಾರ',
    'sahayak.topic4': 'ಗ್ರಾಹಕ ಹಕ್ಕುಗಳು',
    'sahayak.tip': 'ಸಲಹೆ: ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಸಾಧ್ಯವಾದಷ್ಟು ನಿರ್ದಿಷ್ಟವಾಗಿ ಕೇಳಲು ಪ್ರಯತ್ನಿಸಿ ಇದರಿಂದ ನಾವು ನಿಮಗೆ ಹೆಚ್ಚು ಸಹಾಯಕವಾದ ಉತ್ತರವನ್ನು ನೀಡಬಹುದು.',
    
    // Hero Section
    'hero.title': 'ಕಾನೂನು ಸಹಾಯ ಸರಳವಾಗಿಸಲಾಗಿದೆ',
    'hero.subtitle': 'ನಿಮಗೆ ಅರ್ಥವಾಗುವ ರೀತಿಯಲ್ಲಿ ಕಾನೂನು ಮಾಹಿತಿಯನ್ನು ಪಡೆಯಿರಿ',
    'hero.getStarted': 'ಆರಂಭಿಸಿ',
    'hero.learnMore': 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    'hero.name': 'ನಮ್ಮಕೇಂದ್ರ',
    'hero.tagline': 'ಕಾನೂನು ಸಹಾಯ ಸರಳೀಕರಿಸಲಾಗಿದೆ - ಕಾನೂನು ಜ್ಞಾನಕ್ಕಾಗಿ ನಿಮ್ಮ ಸಂಪನ್ಮೂಲ',
    'hero.mission': 'ನಮ್ಮ ಗುರಿ ಎಲ್ಲರಿಗೂ ಕಾನೂನು ಜ್ಞಾನವನ್ನು AI-ಆಧಾರಿತ ಉಪಕರಣಗಳು ಮತ್ತು ಸುಲಭವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದಾದ ವಿಷಯಗಳ ಮೂಲಕ ಲಭ್ಯವಾಗುವಂತೆ ಮಾಡುವುದು.',
    
    // Services Section
    'services.title': 'ನಮ್ಮ ಸೇವೆಗಳು',
    'services.subtitle': 'ನಾವು ಜಟಿಲ ಕಾನೂನು ವಿಷಯಗಳನ್ನು ಸುಲಭ ಮತ್ತು ವಿಶ್ವಾಸದೊಂದಿಗೆ ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲು ಸಹಾಯ ಮಾಡುವ ಉಪಕರಣಗಳನ್ನು ಒದಗಿಸುತ್ತೇವೆ.',
    'services.sahayak.title': 'ನಮ್ಮ ಸಹಾಯಕ',
    'services.sahayak.description': 'ನಮ್ಮ AI-ಆಧಾರಿತ ಚಾಟ್‌ಬಾಟ್ ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಗಳಿಗೆ ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಉತ್ತರಿಸುತ್ತದೆ ಮತ್ತು ಸಾಮಾನ್ಯ ಕಾನೂನು ಕ್ರಮವಿಧಾನಗಳ ಮೂಲಕ ನಿಮಗೆ ಮಾರ್ಗದರ್ಶನ ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    'services.sahayak.feature1': '✔️ಕಾನೂನು ಪ್ರಶ್ನೆಗಳಿಗೆ 24/7 ಉತ್ತರಗಳು',
    'services.sahayak.feature2': '✔️ಜಟಿಲ ಪದಗಳ ಸರಳ ವಿವರಣೆಗಳು',
    'services.sahayak.feature3': '✔️ಕಾರ್ಯವಿಧಾನಗಳಿಗೆ ಹಂತ-ಹಂತದ ಮಾರ್ಗದರ್ಶನ',
    'services.sahayak.button': 'ಸಹಾಯಕನೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
    'services.vidhana.title': 'ನಮ್ಮ ವಿಧಾನ',
    'services.vidhana.description': 'ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲು, ಸರಳೀಕರಿಸಲು ಮತ್ತು ಅವುಗಳನ್ನು ದೈನಂದಿನ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸಲು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    'services.vidhana.feature1': '✔️ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಮತ್ತು ವಿಶ್ಲೇಷಿಸಿ',
    'services.vidhana.feature2': '✔️ಸರಳೀಕೃತ ಸಾರಾಂಶಗಳನ್ನು ಪಡೆಯಿರಿ',
    'services.vidhana.feature3': '✔️ಮುಖ್ಯ ವಿಭಾಗಗಳು ಮತ್ತು ಗಡುವುಗಳನ್ನು ಹೈಲೈಟ್ ಮಾಡಿ',
    'services.vidhana.button': 'ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    
    // How It Works Section
    'how.title': 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    'how.subtitle': 'ನಿಮಗೆ ಅಗತ್ಯವಾದ ಕಾನೂನು ಸಹಾಯವನ್ನು ಪಡೆಯಲು ಸರಳ ಹಂತಗಳು',
    'how.step1.title': 'ಸೇವೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    'how.step1.description': 'ಪ್ರಶ್ನೆಗಳಿಗೆ ನಮ್ಮ ಸಹಾಯಕ ಅಥವಾ ದಾಖಲೆ ಸಹಾಯಕ್ಕೆ ನಮ್ಮ ವಿಧಾನವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.',
    'how.step2.title': 'ಮಾಹಿತಿ ಒದಗಿಸಿ',
    'how.step2.description': 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ ಅಥವಾ ವಿವರಣೆಯ ಅಗತ್ಯವಿರುವ ನಿಮ್ಮ ದಾಖಲೆಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ.',
    'how.step3.title': 'ಸರಳ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ',
    'how.step3.description': 'ನಿಮ್ಮ ಕಾನೂನು ಅಗತ್ಯತೆಗಳಿಗೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸುಲಭವಾದ ವಿವರಣೆಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶನವನ್ನು ಪಡೆಯಿರಿ.',
    
    // Testimonials Section
    'testimonials.title': 'ನಮ್ಮ ಬಳಕೆದಾರರು ಏನು ಹೇಳುತ್ತಾರೆ',
    'testimonials.subtitle': 'ನಾವು ಸಹಾಯ ಮಾಡಿದ ಜನರ ನಿಜವಾದ ಅನುಭವಗಳು',
    'testimonials.1.name': 'ರಮೇಶ್ ಕೆ.',
    'testimonials.1.title': 'ನಿವೃತ್ತ ಶಿಕ್ಷಕ',
    'testimonials.1.content': 'ನಮ್ಮಸಹಾಯಕ ನನಗೆ ನನ್ನ ಪಿಂಚಣಿ ಹಕ್ಕುಗಳನ್ನು ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡಿತು. ಚಾಟ್‌ಬಾಟ್ ಪ್ರತಿಯೊಂದನ್ನೂ ಹಂತ ಹಂತವಾಗಿ ವಿವರಿಸಿತು ಮತ್ತು ನಾನು ಕಾನೂನು ಪರಿಭಾಷೆಯಿಂದ ಅಭಿಭೂತನಾಗಿರಲಿಲ್ಲ.',
    'testimonials.2.name': 'ಲಕ್ಷ್ಮಿ ಎಂ.',
    'testimonials.2.title': 'ಗೃಹಿಣಿ',
    'testimonials.2.content': 'ನಾನು ಸಂಕೀರ್ಣ ಆಸ್ತಿ ಸೂಚನೆಯನ್ನು ಸ್ವೀಕರಿಸಿದಾಗ ಡಾಕ್ಯುಮೆಂಟ್ ಸ್ಕ್ಯಾನರ್ ತುಂಬಾ ಸಹಾಯಕವಾಗಿತ್ತು. ಇದು ಮುಖ್ಯ ದಿನಾಂಕಗಳನ್ನು ಹೈಲೈಟ್ ಮಾಡಿತು ಮತ್ತು ನಾನು ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಯಾವ ಕ್ರಮಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಬೇಕೆಂದು ವಿವರಿಸಿತು.',
    'testimonials.3.name': 'ವೆಂಕಟ್ ಆರ್.',
    'testimonials.3.title': 'ಹಿರಿಯ ನಾಗರಿಕ',
    'testimonials.3.content': 'ನಾನು ಆರೋಗ್ಯ ರಕ್ಷಣೆ ಪ್ರಯೋಜನಗಳ ಬಗ್ಗೆ ಗೊಂದಲದಲ್ಲಿದ್ದಾಗ ನನ್ನ ಮೊಮ್ಮಗ ಈ ಸೇವೆಯನ್ನು ಪ್ರಯತ್ನಿಸಲು ಸೂಚಿಸಿದನು. ದೊಡ್ಡ ಪಠ್ಯ ಆಯ್ಕೆ ಮತ್ತು ಸರಳ ವಿವರಣೆಗಳು ನನಗೆ ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲು ಮತ್ತು ಉತ್ತರಗಳನ್ನು ಪಡೆಯಲು ಸುಲಭವಾಯಿತು.',
    
    // CTA Section
    'cta.title': 'ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧವಾಗಿದ್ದೀರಾ?',
    'cta.subtitle': 'ನಿಮಗೆ ಅರ್ಥವಾಗುವ ಭಾಷೆಯಲ್ಲಿ ನಿಮಗೆ ಬೇಕಾದ ಕಾನೂನು ಸಹಾಯವನ್ನು ಪಡೆಯಿರಿ.',
    'cta.chatButton': 'ನಮ್ಮ ಸಹಾಯಕನೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
    'cta.uploadButton': 'ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    
    // Chat interface
    'chat.title': 'ನಮ್ಮ ಸಹಾಯಕ ಚಾಟ್',
    'chat.subtitle': 'ನಿಮಗಿರುವ ಯಾವುದೇ ಕಾನೂನು ಪ್ರಶ್ನೆಗಳನ್ನು ನನ್ನನ್ನು ಕೇಳಿ',
    'chat.placeholder': 'ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    'chat.send': 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    'chat.startRecording': 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    'chat.stopRecording': 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
    'chat.welcome': 'ನಮಸ್ಕಾರ! ನಾನು ನಮ್ಮ ಸಹಾಯಕ, ನಿಮ್ಮ ಕಾನೂನು ಸಹಾಯಕ. ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    'chat.error': 'ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'chat.speechError': 'ಮಾತನ್ನು ಗುರುತಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'chat.speechNotSupported': 'ನಿಮ್ಮ ಬ್ರೌಸರ್ ಮಾತನ್ನು ಗುರುತಿಸುವಿಕೆಯನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.',
    
    // Document upload
    'document.title': 'ಕಾನೂನು ದಾಖಲೆಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'document.description': 'ಸರಳೀಕೃತ ವಿವರಣೆಯನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಕಾನೂನು ದಾಖಲೆಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ. ನಾವು PDF, DOCX, ಮತ್ತು TXT ಫೈಲ್‌ಗಳನ್ನು 10MB ವರೆಗೆ ಬೆಂಬಲಿಸುತ್ತೇವೆ.',
    'document.drag': 'ನಿಮ್ಮ ಡಾಕ್ಯುಮೆಂಟ್ ಅನ್ನು ಇಲ್ಲಿ ಎಳೆದು ಬಿಡಿ',
    'document.browse': 'ಅಥವಾ ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ (PDF, DOCX, TXT 10MB ವರೆಗೆ)',
    'document.browseButton': 'ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    'document.remove': 'ತೆಗೆದುಹಾಕಿ',
    'document.analyze': 'ಡಾಕ್ಯುಮೆಂಟ್ ವಿಶ್ಲೇಷಿಸಿ',
    'document.processing': 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    'document.howItWorks': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    // NammaVidhana Page
    'vidhana.title': 'ನಮ್ಮ ವಿಧಾನ ಡಾಕ್ಯುಮೆಂಟ್ ಸರಳೀಕರಣ',
    'vidhana.description': 'ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಅವುಗಳನ್ನು ಸರಳ, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸುಲಭವಾದ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸಿ. ನಮ್ಮ AI ಜಟಿಲ ಕಾನೂನು ಜಾರ್ಗಾನ್ ಅನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    'vidhana.service': 'ಡಾಕ್ಯುಮೆಂಟ್ ಸರಳೀಕರಣ ಸೇವೆ',
    'vidhana.serviceDesc': 'ನಮ್ಮ ಸಾಧನವು ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ ಮತ್ತು ಅವುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸುಲಭವಾದ ಸರಳ ಭಾಷೆಗೆ ಅನುವಾದಿಸುತ್ತದೆ. ನೀವು ಪಡೆಯುವಿರಿ:',
    'vidhana.feature1': 'ಸಂಪೂರ್ಣ ದಾಖಲೆಯ ಸರಳೀಕೃತ ಸಾರಾಂಶ',
    'vidhana.feature2': 'ಪ್ರಮುಖ ಅಂಶಗಳು ಮತ್ತು ಮಹತ್ವದ ಮಾಹಿತಿಯನ್ನು ಹೈಲೈಟ್ ಮಾಡಲಾಗಿದೆ',
    'vidhana.feature3': 'ಬಳಸಿದ ಕಾನೂನು ಪದಗಳ ಸ್ಪಷ್ಟ ವಿವರಣೆ',
    'vidhana.feature4': 'ಮುಖ್ಯ ದಿನಾಂಕಗಳು, ಗಡುವುಗಳು ಮತ್ತು ಅಗತ್ಯವಿರುವ ಕ್ರಮಗಳು',
    'vidhana.benefit': 'ಈ ಸೇವೆಯು ಮೂಲಭೂತ ವಿವರಣೆಗಳಿಗಾಗಿ ದುಬಾರಿ ವಕೀಲರನ್ನು ನೇಮಿಸಿಕೊಳ್ಳದೆ ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    'vidhana.documentTypes': 'ನೀವು ಅಪ್ಲೋಡ್ ಮಾಡಬಹುದಾದ ದಾಖಲೆಗಳು',
    'vidhana.docType1': 'ನ್ಯಾಯಾಲಯದ ನೋಟೀಸುಗಳು ಮತ್ತು ಆದೇಶಗಳು',
    'vidhana.docType2': 'ಕಾನೂನು ಒಪ್ಪಂದಗಳು ಮತ್ತು ಒಪ್ಪಂದಗಳು',
    'vidhana.docType3': 'ಸರ್ಕಾರದ ನೋಟೀಸುಗಳು',
    'vidhana.docType4': 'ಆಸ್ತಿ ದಾಖಲೆಗಳು',
    
    // Page titles
    'page.vidhana.title': 'ನಮ್ಮ ವಿಧಾನ ಡಾಕ್ಯುಮೆಂಟ್ ಸಿಂಪ್ಲಿಫೈಯರ್',
    'page.vidhana.description': 'ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಅವುಗಳನ್ನು ಸರಳ, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸುಲಭವಾದ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸಿ. ನಮ್ಮ AI ಜಟಿಲ ಕಾನೂನು ಜಾರ್ಗಾನ್ ಅನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    'page.vidhana.service': 'ಡಾಕ್ಯುಮೆಂಟ್ ಸಿಂಪ್ಲಿಫಿಕೇಶನ್ ಸೇವೆ',
    'page.vidhana.serviceDesc': 'ನಮ್ಮ ಸಾಧನವು ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ ಮತ್ತು ಅವುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸುಲಭವಾದ ಸರಳ ಭಾಷೆಗೆ ಅನುವಾದಿಸುತ್ತದೆ. ನೀವು ಪಡೆಯುವಿರಿ:',
    'page.vidhana.feature1': 'ಸಂಪೂರ್ಣ ದಾಖಲೆಯ ಸರಳೀಕೃತ ಸಾರಾಂಶ',
    'page.vidhana.feature2': 'ಪ್ರಮುಖ ಅಂಶಗಳು ಮತ್ತು ಮಹತ್ವದ ಮಾಹಿತಿಯನ್ನು ಹೈಲೈಟ್ ಮಾಡಲಾಗಿದೆ',
    'page.vidhana.feature3': 'ಬಳಸಿದ ಕಾನೂನು ಪದಗಳ ಸ್ಪಷ್ಟ ವಿವರಣೆ',
    'page.vidhana.feature4': 'ಮುಖ್ಯ ದಿನಾಂಕಗಳು, ಗಡುವುಗಳು ಮತ್ತು ಅಗತ್ಯವಿರುವ ಕ್ರಮಗಳು',
    'page.vidhana.benefit': 'ಈ ಸೇವೆಯು ಮೂಲಭೂತ ವಿವರಣೆಗಳಿಗಾಗಿ ದುಬಾರಿ ವಕೀಲರನ್ನು ನೇಮಿಸಿಕೊಳ್ಳದೆ ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    'page.vidhana.documentTypes': 'ನೀವು ಅಪ್ಲೋಡ್ ಮಾಡಬಹುದಾದ ದಾಖಲೆಗಳು',
    'page.vidhana.docType1': 'ನ್ಯಾಯಾಲಯದ ನೋಟೀಸುಗಳು ಮತ್ತು ಆದೇಶಗಳು',
    'page.vidhana.docType2': 'ಕಾನೂನು ಒಪ್ಪಂದಗಳು ಮತ್ತು ಒಪ್ಪಂದಗಳು',
    'page.vidhana.docType3': 'ಸರ್ಕಾರದ ನೋಟೀಸುಗಳು',
    'page.vidhana.docType4': 'ಆಸ್ತಿ ದಾಖಲೆಗಳು',
    
    // Footer
    'footer.quickLinks': 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    'footer.services': 'ನಮ್ಮ ಸೇವೆಗಳು',
    'footer.contact': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    'footer.address': '123 ಮುಖ್ಯ ರಸ್ತೆ, ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ',
    'footer.phone': '+91 123 456 7890',
    'footer.email': 'info@nammasahayak.org',
    'footer.copyright': 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    'footer.privacyPolicy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
    'footer.terms': 'ಸೇವಾ ನಿಯಮಗಳು',
    'footer.accessibility': 'ಪ್ರವೇಶಿಸುವಿಕೆ',
    'footer.slogan': 'ಕಾನೂನು ಜ್ಞಾನವನ್ನು ಎಲ್ಲರಿಗೂ ಲಭ್ಯವಾಗುವಂತೆ ಮಾಡುವುದು',
    
    // Accessibility Page
    'accessibility.title': 'ಪ್ರವೇಶಿಸುವಿಕೆ ಹೇಳಿಕೆ',
    'accessibility.lastUpdated': 'ಕೊನೆಯ ನವೀಕರಣ: ಏಪ್ರಿಲ್ 9, 2025',
    'accessibility.commitment.title': 'ಪ್ರವೇಶಿಸುವಿಕೆಗೆ ನಮ್ಮ ಬದ್ಧತೆ',
    'accessibility.commitment.text1': 'ನಮ್ಮಕೇಂದ್ರದಲ್ಲಿ, ನಾವು ಅಂಗವಿಕಲತೆ ಹೊಂದಿರುವ ವ್ಯಕ್ತಿಗಳಿಗೆ ಡಿಜಿಟಲ್ ಪ್ರವೇಶವನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಬದ್ಧರಾಗಿದ್ದೇವೆ. ನಾವು ಎಲ್ಲರಿಗೂ ಬಳಕೆದಾರರ ಅನುಭವವನ್ನು ನಿರಂತರವಾಗಿ ಸುಧಾರಿಸುತ್ತಿದ್ದೇವೆ ಮತ್ತು ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಮಾನದಂಡಗಳನ್ನು ಅನ್ವಯಿಸುತ್ತಿದ್ದೇವೆ.',
    'accessibility.commitment.text2': 'ಎಲ್ಲಾ ನಾಗರಿಕರಿಗೆ, ವಿಶೇಷವಾಗಿ ಹಿರಿಯರು ಮತ್ತು ಅನುಕೂಲವಿಲ್ಲದವರಿಗೆ ಕಾನೂನು ಮಾಹಿತಿಯನ್ನು ಪ್ರವೇಶಿಸುವುದು ನಮ್ಮ ಉದ್ದೇಶವಾಗಿದೆ. ಇದನ್ನು ಸಾಧಿಸಲು, ನಾವು ನಮ್ಮ ವೇದಿಕೆಯಲ್ಲಿ ಪ್ರವೇಶ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ನೇರವಾಗಿ ನಿರ್ಮಿಸಿದ್ದೇವೆ ಮತ್ತು ಅವುಗಳನ್ನು ಸುಧಾರಿಸಲು ನಿರಂತರವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತೇವೆ.',
    'accessibility.features.title': 'ಪ್ರವೇಶ ವೈಶಿಷ್ಟ್ಯಗಳು',
    'accessibility.features.intro': 'ನಮ್ಮಕೇಂದ್ರವು ಈ ಕೆಳಗಿನ ಪ್ರವೇಶ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಒಳಗೊಂಡಿದೆ:',
    'accessibility.features.fontSizeControl': 'ಫಾಂಟ್ ಗಾತ್ರ ನಿಯಂತ್ರಣಗಳು: ಉತ್ತಮ ಓದುವಿಕೆಗಾಗಿ ಪಠ್ಯದ ಗಾತ್ರವನ್ನು ಸುಲಭವಾಗಿ ಹೆಚ್ಚಿಸಿ ಅಥವಾ ಕಡಿಮೆ ಮಾಡಿ.',
    'accessibility.features.clearDesign': 'ಸ್ಪಷ್ಟ ವಿನ್ಯಾಸ: ನಮ್ಮ ಇಂಟರ್ಫೇಸ್ ಅನ್ನು ಸ್ಪಷ್ಟತೆ ಮತ್ತು ಸರಳತೆಯನ್ನು ಮನಸ್ಸಿನಲ್ಲಿಟ್ಟುಕೊಂಡು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.',
    'accessibility.features.highContrast': 'ಅಧಿಕ ವ್ಯತ್ಯಾಸ: ನಮ್ಮ ವಿನ್ಯಾಸವು ಓದುವಿಕೆಗಾಗಿ ಸೂಕ್ತವಾದ ಬಣ್ಣದ ವ್ಯತ್ಯಾಸದ ಅನುಪಾತಗಳನ್ನು ಕಾಯ್ದುಕೊಳ್ಳುತ್ತದೆ.',
    'accessibility.features.textToSpeech': 'ಪಠ್ಯದಿಂದ ಮಾತು: ಶ್ರವಣ ಮಾಹಿತಿಯನ್ನು ಆದ್ಯತೆ ನೀಡುವವರಿಗೆ ಪಠ್ಯದಿಂದ ಮಾತಿಗೆ ಸಾಮರ್ಥ್ಯಗಳು.',
    'accessibility.features.keyboardNav': 'ಕೀಬೋರ್ಡ್ ನ್ಯಾವಿಗೇಶನ್: ಮೌಸ್ ಬಳಸಲು ಸಾಧ್ಯವಿಲ್ಲದ ಬಳಕೆದಾರರಿಗೆ ಸಂಪೂರ್ಣ ಕೀಬೋರ್ಡ್ ಪ್ರವೇಶ.',
    'accessibility.features.screenReader': 'ಸ್ಕ್ರೀನ್ ರೀಡರ್ ಹೊಂದಾಣಿಕೆ: ನಮ್ಮ ವೆಬ್‌ಸೈಟ್ ಅನ್ನು ಸ್ಕ್ರೀನ್ ರೀಡರ್‌ಗಳಿಗೆ ಅನುಕೂಲಿಸಲಾಗಿದೆ.',
    'accessibility.features.simpleLanguage': 'ಸರಳ ಭಾಷೆ: ನಾವು ಸಾಧ್ಯವಾದಾಗಲೆಲ್ಲಾ ಸರಳ, ನೇರವಾದ ಭಾಷೆಯನ್ನು ಬಳಸುತ್ತೇವೆ.',
    'accessibility.conformance.title': 'ಅನುಕೂಲತೆ ಸ್ಥಿತಿ',
    'accessibility.conformance.text1': 'ವೆಬ್ ಕಂಟೆಂಟ್ ಆಕ್ಸೆಸಿಬಿಲಿಟಿ ಗೈಡ್‌ಲೈನ್ಸ್ (WCAG) ಅಂಗವಿಕಲತೆ ಹೊಂದಿರುವ ವ್ಯಕ್ತಿಗಳಿಗೆ ಪ್ರವೇಶವನ್ನು ಸುಧಾರಿಸಲು ವಿನ್ಯಾಸಕರು ಮತ್ತು ಡೆವಲಪರ್‌ಗಳಿಗೆ ಅಗತ್ಯತೆಗಳನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುತ್ತದೆ. ಇದು ಮೂರು ಮಟ್ಟದ ಅನುರೂಪತೆಯನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುತ್ತದೆ: ಮಟ್ಟ A, ಮಟ್ಟ AA ಮತ್ತು ಮಟ್ಟ AAA.',
    'accessibility.conformance.text2': 'ನಮ್ಮಕೇಂದ್ರವು WCAG 2.1 ಮಟ್ಟ AA ಯೊಂದಿಗೆ ಭಾಗಶಃ ಅನುಕೂಲವಾಗಿದೆ. ಆಂಶಿಕವಾಗಿ ಅನುರೂಪವಾಗಿದೆ ಎಂದರೆ ವಿಷಯದ ಕೆಲವು ಭಾಗಗಳು ಪ್ರವೇಶದ ಮಾನದಂಡಕ್ಕೆ ಸಂಪೂರ್ಣವಾಗಿ ಅನುಗುಣವಾಗಿಲ್ಲ ಎಂದರ್ಥ.',
    'accessibility.howToUse.title': 'ನಮ್ಮ ಪ್ರವೇಶ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಹೇಗೆ ಬಳಸುವುದು',
    'accessibility.howToUse.fontSizeTitle': 'ಫಾಂಟ್ ಗಾತ್ರ ನಿಯಂತ್ರಣ',
    'accessibility.howToUse.fontSizeText': 'ಪ್ರತಿ ಪುಟದ ಹೆಡರ್‌ನಲ್ಲಿರುವ ಫಾಂಟ್ ಗಾತ್ರದ ನಿಯಂತ್ರಣಗಳನ್ನು ಬಳಸಿಕೊಂಡು ನೀವು ಪಠ್ಯದ ಗಾತ್ರವನ್ನು ಹೊಂದಿಸಬಹುದು. ಕಡಿಮೆ ಮಾಡಲು (-) ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ, ಡೀಫಾಲ್ಟ್ ಗಾತ್ರಕ್ಕೆ ಮರುಹೊಂದಿಸಲು (A) ಬಟನ್ ಅಥವಾ ಫಾಂಟ್ ಗಾತ್ರವನ್ನು ಹೆಚ್ಚಿಸಲು (+) ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    'accessibility.howToUse.clearDesignTitle': 'ಸ್ಪಷ್ಟ ವಿನ್ಯಾಸ',
    'accessibility.howToUse.clearDesignText': 'ನಮ್ಮ ಇಂಟರ್ಫೇಸ್ ನಿರಂತರ, ಸಹಜವಾದ ನ್ಯಾವಿಗೇಶನ್ ಮತ್ತು ಸ್ಪಷ್ಟ ದೃಶ್ಯ ಪದಾನುಕ್ರಮವನ್ನು ಹೊಂದಿದೆ, ಇದು ಜ್ಞಾನಾತ್ಮಕ ಅಂಗವೈಕಲ್ಯ ಹೊಂದಿರುವವರು ಸೇರಿದಂತೆ ಎಲ್ಲಾ ಬಳಕೆದಾರರಿಗೆ ಬಳಕೆಯನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ.',
    'accessibility.howToUse.keyboardNavTitle': 'ಕೀಬೋರ್ಡ್ ನ್ಯಾವಿಗೇಶನ್',
    'accessibility.howToUse.keyboardNavText': 'ನೀವು ನಿಮ್ಮ ಕೀಬೋರ್ಡ್ ಅನ್ನು ಮಾತ್ರ ಬಳಸಿಕೊಂಡು ನಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ನ್ಯಾವಿಗೇಟ್ ಮಾಡಬಹುದು. ಲಿಂಕ್‌ಗಳು ಮತ್ತು ನಿಯಂತ್ರಣಗಳ ಮೂಲಕ ಮುಂದೆ ಸರಿಯಲು Tab ಬಳಸಿ, ಹಿಂದೆ ಸರಿಯಲು Shift+Tab, ಲಿಂಕ್‌ಗಳು ಮತ್ತು ಬಟನ್‌ಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲು Enter ಮತ್ತು ಚೆಕ್‌ಬಾಕ್ಸ್‌ಗಳು ಮತ್ತು ರೇಡಿಯೊ ಬಟನ್‌ಗಳನ್ನು ಟಾಗಲ್ ಮಾಡಲು Space ಅನ್ನು ಬಳಸಿ.',
    'accessibility.limitations.title': 'ಮಿತಿಗಳು ಮತ್ತು ಪರ್ಯಾಯಗಳು',
    'accessibility.limitations.intro': 'ನಮ್ಮಕೇಂದ್ರದ ಪ್ರವೇಶವನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನಮ್ಮ ಅತ್ಯುತ್ತಮ ಪ್ರಯತ್ನಗಳ ಹೊರತಾಗಿಯೂ, ಕೆಲವು ಮಿತಿಗಳಿರಬಹುದು. ಕೆಳಗೆ ತಿಳಿದಿರುವ ಮಿತಿಗಳು ಮತ್ತು ಸಂಭಾವ್ಯ ಪರಿಹಾರಗಳ ವಿವರಣೆಯಿದೆ:',
    'accessibility.limitations.item1': 'ನಮ್ಮ ಕೆಲವು ಹಳೆಯ PDF ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳು ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರವೇಶಿಸುವಂತಿಲ್ಲ. ನಾವು ಈ ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳನ್ನು ನವೀಕರಿಸುವ ಕೆಲಸದಲ್ಲಿದ್ದೇವೆ, ಆದರೆ ನೀವು ಪ್ರವೇಶಿಸಲಾಗದ PDF ಅನ್ನು ಎದುರಿಸಿದರೆ, ದಯವಿಟ್ಟು ಸಹಾಯಕ್ಕಾಗಿ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    'accessibility.limitations.item2': 'ನಮ್ಮ ಕೆಲವು ಸಂವಾದಾತ್ಮಕ ವೈಶಿಷ್ಟ್ಯಗಳು ನಿರ್ದಿಷ್ಟ ಅಂಗವೈಕಲ್ಯಗಳನ್ನು ಹೊಂದಿರುವ ಬಳಕೆದಾರರಿಗೆ ಸವಾಲಿನದಾಗಿರಬಹುದು. ನಾವು ಸಾಧ್ಯವಾದಾಗಲೆಲ್ಲಾ ಅದೇ ಮಾಹಿತಿಯನ್ನು ಪ್ರವೇಶಿಸಲು ಪರ್ಯಾಯ ವಿಧಾನಗಳನ್ನು ಒದಗಿಸುತ್ತೇವೆ.',
    'accessibility.feedback.title': 'ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಸಂಪರ್ಕ ಮಾಹಿತಿ',
    'accessibility.feedback.text': 'ನಮ್ಮಕೇಂದ್ರದ ಪ್ರವೇಶಿಸುವಿಕೆಯ ಕುರಿತು ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ನಾವು ಸ್ವಾಗತಿಸುತ್ತೇವೆ. ನೀವು ಪ್ರವೇಶ ತಡೆಗಳನ್ನು ಎದುರಿಸಿದರೆ ದಯವಿಟ್ಟು ನಮಗೆ ತಿಳಿಸಿ:',
    'accessibility.feedback.item1': 'ಯಾವುದೇ ಪ್ರವೇಶ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಲು ಅಥವಾ ಸಹಾಯವನ್ನು ಕೋರಲು ನಮ್ಮ ಸಂಪರ್ಕ ಫಾರ್ಮ್ ಅನ್ನು ಬಳಸಿ.',
    'accessibility.feedback.item2': 'ನಮಗೆ accessibility@nammakendra.org ಗೆ ಇಮೇಲ್ ಮಾಡಿ.',
    'accessibility.feedback.item3': 'ನಾವು 2 ವ್ಯಾಪಾರ ದಿನಗಳೊಳಗೆ ಪ್ರತಿಕ್ರಿಯಿಸಲು ಗುರಿ ಹೊಂದಿದ್ದೇವೆ.',
    
    // Terms of Service Page
    'terms.title': 'ಸೇವಾ ನಿಯಮಗಳು',
    'terms.lastUpdated': 'ಕೊನೆಯ ನವೀಕರಣ: ಏಪ್ರಿಲ್ 9, 2025',
    'terms.section1.title': '1. ಪರಿಚಯ',
    'terms.section1.text': 'ನಮ್ಮಕೇಂದ್ರಕ್ಕೆ ಸುಸ್ವಾಗತ. ಈ ಸೇವಾ ನಿಯಮಗಳು ("ನಿಯಮಗಳು") ನಮ್ಮ ವೆಬ್‌ಸೈಟ್, ಅಪ್ಲಿಕೇಶನ್‌ಗಳು ಮತ್ತು ಸೇವೆಗಳನ್ನು (ಒಟ್ಟಾಗಿ, "ಸೇವೆಗಳು") ನಿಮ್ಮ ಬಳಕೆಯನ್ನು ನಿಯಂತ್ರಿಸುತ್ತವೆ. ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸುವ ಅಥವಾ ಬಳಸುವ ಮೂಲಕ, ನೀವು ಈ ನಿಯಮಗಳಿಗೆ ಬದ್ಧರಾಗಿರಲು ಒಪ್ಪುತ್ತೀರಿ. ನೀವು ನಿಯಮಗಳ ಯಾವುದೇ ಭಾಗವನ್ನು ಒಪ್ಪದಿದ್ದರೆ, ನೀವು ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸಬಾರದು.',
    'terms.section2.title': '2. ಸೇವೆಗಳ ಬಳಕೆ',
    'terms.section2.text1': 'ನಮ್ಮ ಸೇವೆಗಳು ಕಾನೂನು ವಿಷಯಗಳು ಮತ್ತು ಸರ್ಕಾರಿ ಸೇವೆಗಳ ಬಗ್ಗೆ ಮಾಹಿತಿ ಮತ್ತು ಸಹಾಯವನ್ನು ಒದಗಿಸಲು ಉದ್ದೇಶಿಸಲಾಗಿದೆ. ಆದಾಗ್ಯೂ, ನಮ್ಮ ಸೇವೆಗಳ ಮೂಲಕ ಒದಗಿಸಲಾದ ಮಾಹಿತಿಯು ಕಾನೂನು ಸಲಹೆಯಲ್ಲ ಮತ್ತು ಅದನ್ನು ಅವಲಂಬಿಸಬಾರದು. ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ಸಲಹೆಗಾಗಿ ಅರ್ಹ ಕಾನೂನು ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಬೇಕೆಂದು ನಾವು ದೃಢವಾಗಿ ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ.',
    'terms.section2.text2': 'ನೀವು ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಕಾನೂನುಬದ್ಧ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ ಮತ್ತು ಇತರ ಬಳಕೆದಾರರಿಗೆ ಸೇವೆಗಳ ಬಳಕೆ ಮತ್ತು ಆನಂದವನ್ನು ಉಲ್ಲಂಘಿಸದ, ನಿರ್ಬಂಧಿಸುವ ಅಥವಾ ತಡೆಯದ ರೀತಿಯಲ್ಲಿ ಬಳಸಲು ಒಪ್ಪುತ್ತೀರಿ. ನಿಷೇಧಿತ ನಡವಳಿಕೆಯಲ್ಲಿ ಇತರ ಬಳಕೆದಾರರನ್ನು ಕಿರುಕುಳ ನೀಡುವುದು ಅಥವಾ ಮಾನಸಿಕ ನೋವು ಉಂಟುಮಾಡುವುದು, ಅಶ್ಲೀಲ ಅಥವಾ ಅಪಮಾನಕರ ವಿಷಯವನ್ನು ರವಾನಿಸುವುದು ಅಥವಾ ನಮ್ಮ ಸೇವೆಗಳೊಳಗಿನ ಸಂವಾದದ ಸಾಮಾನ್ಯ ಹರಿವನ್ನು ಕದಡುವುದು ಸೇರಿವೆ.',
    'terms.section3.title': '3. ಖಾತೆಗಳು',
    'terms.section3.text1': 'ನೀವು ನಮ್ಮೊಂದಿಗೆ ಖಾತೆಯನ್ನು ರಚಿಸಿದಾಗ, ನೀವು ಯಾವಾಗಲೂ ನಿಖರವಾದ, ಪೂರ್ಣ ಮತ್ತು ಪ್ರಸ್ತುತ ಮಾಹಿತಿಯನ್ನು ಒದಗಿಸಬೇಕು. ಹಾಗೆ ಮಾಡಲು ವಿಫಲವಾದರೆ ಅದು ನಿಯಮಗಳ ಉಲ್ಲಂಘನೆಯಾಗುತ್ತದೆ, ಇದರ ಪರಿಣಾಮವಾಗಿ ನಮ್ಮ ಸೇವೆಗಳಲ್ಲಿ ನಿಮ್ಮ ಖಾತೆಯನ್ನು ತಕ್ಷಣವೇ ಮುಚ್ಚಬಹುದು.',
    'terms.section3.text2': 'ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ನೀವು ಬಳಸುವ ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತು ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಅಡಿಯಲ್ಲಿರುವ ಯಾವುದೇ ಚಟುವಟಿಕೆಗಳು ಅಥವಾ ಕ್ರಿಯೆಗಳಿಗೆ ನೀವು ಜವಾಬ್ದಾರರಾಗಿರುತ್ತೀರಿ. ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಅನ್ನು ಯಾವುದೇ ಮೂರನೇ ವ್ಯಕ್ತಿಗೆ ಬಹಿರಂಗಪಡಿಸದಂತೆ ನೀವು ಒಪ್ಪುತ್ತೀರಿ. ಭದ್ರತೆಯ ಯಾವುದೇ ಉಲ್ಲಂಘನೆ ಅಥವಾ ನಿಮ್ಮ ಖಾತೆಯ ಅನಧಿಕೃತ ಬಳಕೆಯ ಬಗ್ಗೆ ತಿಳಿದ ತಕ್ಷಣ ನೀವು ನಮಗೆ ತಿಳಿಸಬೇಕು.',
    'terms.section4.title': '4. ಬೌದ್ಧಿಕ ಸ್ವತ್ತು',
    'terms.section4.text': 'ಸೇವೆಗಳು ಮತ್ತು ಅವುಗಳ ಮೂಲ ವಿಷಯ, ವೈಶಿಷ್ಟ್ಯಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ಷಮತೆಯು ನಮ್ಮಕೇಂದ್ರ ಮತ್ತು ಅದರ ಪರವಾನಗಿ ನೀಡುವವರ ವಿಶೇಷ ಆಸ್ತಿಯಾಗಿರುತ್ತದೆ. ಸೇವೆಗಳನ್ನು ಭಾರತ ಮತ್ತು ವಿದೇಶಿ ದೇಶಗಳ ಕಾಪಿರೈಟ್, ಟ್ರೇಡ್‌ಮಾರ್ಕ್ ಮತ್ತು ಇತರ ಕಾನೂನುಗಳಿಂದ ರಕ್ಷಿಸಲಾಗಿದೆ. ನಮ್ಮಕೇಂದ್ರದ ಪೂರ್ವಲಿಖಿತ ಒಪ್ಪಿಗೆಯಿಲ್ಲದೆ ನಮ್ಮ ಟ್ರೇಡ್‌ಮಾರ್ಕ್‌ಗಳು ಮತ್ತು ವ್ಯಾಪಾರ ಉಡುಪನ್ನು ಯಾವುದೇ ಉತ್ಪನ್ನ ಅಥವಾ ಸೇವೆಯೊಂದಿಗೆ ಬಳಸಬಾರದು.',
    'terms.section5.title': '5. ಬಳಕೆದಾರರು ಸೃಷ್ಟಿಸಿದ ವಿಷಯ',
    'terms.section5.text1': 'ನಮ್ಮ ಸೇವೆಗಳಿಗೆ ವಿಷಯವನ್ನು ಸಲ್ಲಿಸುವ ಮೂಲಕ, ನೀವು ನಮಗೆ ಜಾಗತಿಕ, ಅನನ್ಯವಲ್ಲದ, ರಾಯಲ್ಟಿ-ಮುಕ್ತ ಪರವಾನಗಿಯನ್ನು ನೀಡುತ್ತೀರಿ, ಬಳಸಲು, ಪುನರುತ್ಪಾದಿಸಲು, ಮಾರ್ಪಡಿಸಲು, ಹೊಂದಿಕೊಳ್ಳಲು, ಪ್ರಕಟಿಸಲು, ಅನುವಾದಿಸಲು, ವ್ಯುತ್ಪನ್ನ ಕೆಲಸಗಳನ್ನು ರಚಿಸಲು, ವಿತರಿಸಲು ಮತ್ತು ಯಾವುದೇ ಮಾಧ್ಯಮದಲ್ಲಿ ಅಂತಹ ವಿಷಯವನ್ನು ಪ್ರದರ್ಶಿಸಲು.',
    'terms.section5.text2': 'ನೀವು ಪ್ರತಿನಿಧಿಸುತ್ತೀರಿ ಮತ್ತು ಖಾತರಿಪಡಿಸುತ್ತೀರಿ: (i) ವಿಷಯವು ನಿಮ್ಮದು ಅಥವಾ ನೀವು ಅದನ್ನು ಬಳಸಲು ಮತ್ತು ಈ ನಿಯಮಗಳಲ್ಲಿ ಒದಗಿಸಿದಂತೆ ನಮಗೆ ಹಕ್ಕುಗಳು ಮತ್ತು ಪರವಾನಗಿಯನ್ನು ನೀಡಲು ಹಕ್ಕನ್ನು ಹೊಂದಿದ್ದೀರಿ, ಮತ್ತು (ii) ನಿಮ್ಮ ವಿಷಯದ ಸಲ್ಲಿಕೆಯು ಯಾವುದೇ ವ್ಯಕ್ತಿಯ ಗೌಪ್ಯತೆ ಹಕ್ಕುಗಳು, ಪ್ರಚಾರದ ಹಕ್ಕುಗಳು, ಕಾಪಿರೈಟ್‌ಗಳು, ಒಪ್ಪಂದದ ಹಕ್ಕುಗಳು ಅಥವಾ ಯಾವುದೇ ಇತರ ಹಕ್ಕುಗಳನ್ನು ಉಲ್ಲಂಘಿಸುವುದಿಲ್ಲ.',
    'terms.section6.title': '6. ಹಕ್ಕುತ್ಯಾಗ',
    'terms.section6.text1': 'ಸೇವೆಗಳ ನಿಮ್ಮ ಬಳಕೆಯು ನಿಮ್ಮ ಸ್ವಂತ ಅಪಾಯದಲ್ಲಿದೆ. ಸೇವೆಗಳನ್ನು "ಹೇಗಿದೆಯೋ ಹಾಗೆ" ಮತ್ತು "ಲಭ್ಯವಿರುವಂತೆ" ಒದಗಿಸಲಾಗುತ್ತದೆ. ಸೇವೆಗಳನ್ನು ಯಾವುದೇ ರೀತಿಯ ಖಾತರಿಗಳಿಲ್ಲದೆ ಒದಗಿಸಲಾಗುತ್ತದೆ, ಸ್ಪಷ್ಟವಾದ ಅಥವಾ ಪರೋಕ್ಷವಾಗಿ, ಮಾರುಕಟ್ಟೆ ಮಾಡುವಿಕೆಯ ಪರೋಕ್ಷ ಖಾತರಿಗಳು, ನಿರ್ದಿಷ್ಟ ಉದ್ದೇಶಕ್ಕಾಗಿ ಸೂಕ್ತತೆ, ಉಲ್ಲಂಘನೆ ಮಾಡದಿರುವುದು ಅಥವಾ ಕಾರ್ಯನಿರ್ವಹಣೆಯ ಕೋರ್ಸ್ ಸೇರಿದಂತೆ, ಆದರೆ ಇವುಗಳಿಗೆ ಸೀಮಿತವಾಗಿರದೆ.',
    'terms.section6.text2': 'ನಮ್ಮಕೇಂದ್ರ, ಅದರ ಅಂಗಸಂಸ್ಥೆಗಳು, ಸಂಬಂಧಿತ ಸಂಸ್ಥೆಗಳು ಮತ್ತು ಪರವಾನಗಿದಾರರು ಇದನ್ನು ಖಾತರಿಪಡಿಸುವುದಿಲ್ಲ: (i) ಸೇವೆಗಳು ಅಡಚಣೆಯಿಲ್ಲದೆ, ಸುರಕ್ಷಿತವಾಗಿ, ಅಥವಾ ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ ಸಮಯದಲ್ಲಿ ಅಥವಾ ಸ್ಥಳದಲ್ಲಿ ಲಭ್ಯವಿರುತ್ತದೆ; (ii) ಯಾವುದೇ ದೋಷಗಳು ಅಥವಾ ನ್ಯೂನತೆಗಳನ್ನು ಸರಿಪಡಿಸಲಾಗುತ್ತದೆ; (iii) ಸೇವೆಗಳು ವೈರಸ್‌ಗಳು ಅಥವಾ ಇತರ ಹಾನಿಕಾರಕ ಘಟಕಗಳಿಂದ ಮುಕ್ತವಾಗಿವೆ; ಅಥವಾ (iv) ಸೇವೆಗಳನ್ನು ಬಳಸುವ ಫಲಿತಾಂಶಗಳು ನಿಮ್ಮ ಅಗತ್ಯತೆಗಳನ್ನು ಪೂರೈಸುತ್ತವೆ.',
    'terms.section7.title': '7. ಹೊಣೆಗಾರಿಕೆಯ ಮಿತಿ',
    'terms.section7.text': 'ಯಾವುದೇ ಸಂದರ್ಭದಲ್ಲೂ ನಮ್ಮಕೇಂದ್ರ, ಅಥವಾ ಅದರ ನಿರ್ದೇಶಕರು, ನೌಕರರು, ಪಾಲುದಾರರು, ಏಜೆಂಟರು, ಪೂರೈಕೆದಾರರು ಅಥವಾ ಸಂಬಂಧಿತ ಸಂಸ್ಥೆಗಳು ಯಾವುದೇ ಪರೋಕ್ಷ, ಆಕಸ್ಮಿಕ, ವಿಶೇಷ, ಪರಿಣಾಮಕಾರಿ ಅಥವಾ ಶಿಕ್ಷಾತ್ಮಕ ಹಾನಿಗಳಿಗೆ ಜವಾಬ್ದಾರರಾಗಿರುವುದಿಲ್ಲ, ಲಾಭಗಳ ನಷ್ಟ, ಡೇಟಾ, ಬಳಕೆ, ಒಳ್ಳೆಯ ಮಾತು ಅಥವಾ ಇತರ ಅಮೂರ್ತ ನಷ್ಟಗಳು ಸೇರಿದಂತೆ, ಮಿತಿಯಿಲ್ಲದೆ, (i) ನಿಮ್ಮ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸುವುದು ಅಥವಾ ಬಳಸುವುದು ಅಥವಾ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಅಥವಾ ಬಳಸಲು ಸಾಧ್ಯವಾಗದಿರುವುದರಿಂದ ಉಂಟಾಗುವ; (ii) ಸೇವೆಗಳಲ್ಲಿನ ಯಾವುದೇ ಮೂರನೇ ವ್ಯಕ್ತಿಯ ನಡವಳಿಕೆ ಅಥವಾ ವಿಷಯ; (iii) ಸೇವೆಗಳಿಂದ ಪಡೆದ ಯಾವುದೇ ವಿಷಯ; ಮತ್ತು (iv) ನಿಮ್ಮ ಪ್ರಸಾರಗಳ ಅಥವಾ ವಿಷಯದ ಅನಧಿಕೃತ ಪ್ರವೇಶ, ಬಳಕೆ, ಅಥವಾ ಬದಲಾವಣೆ, ಖಾತರಿ, ಒಪ್ಪಂದ, ದೋಷ (ನಿರ್ಲಕ್ಷ್ಯ ಸೇರಿದಂತೆ) ಅಥವಾ ಯಾವುದೇ ಇತರ ಕಾನೂನು ಸಿದ್ಧಾಂತದ ಮೇಲೆ ಆಧಾರಿತವಾಗಿದೆಯೇ, ಅಂತಹ ಹಾನಿಯ ಸಾಧ್ಯತೆಯ ಬಗ್ಗೆ ನಮಗೆ ತಿಳಿಸಿದರೂ ಸಹ.',
    'terms.section8.title': '8. ಬದಲಾವಣೆಗಳು',
    'terms.section8.text1': 'ನಾವು ನಮ್ಮ ಸ್ವಂತ ವಿವೇಚನೆಯಿಂದ ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಈ ನಿಯಮಗಳನ್ನು ಮಾರ್ಪಡಿಸುವ ಅಥವಾ ಬದಲಾಯಿಸುವ ಹಕ್ಕನ್ನು ಕಾಯ್ದಿರಿಸಿಕೊಳ್ಳುತ್ತೇವೆ. ಪರಿಷ್ಕರಣೆಯು ಭೌತಿಕವಾಗಿದ್ದರೆ, ಯಾವುದೇ ಹೊಸ ನಿಯಮಗಳು ಜಾರಿಗೆ ಬರುವ ಮೊದಲು ಕನಿಷ್ಠ 30 ದಿನಗಳ ಸೂಚನೆಯನ್ನು ನೀಡಲು ನಾವು ಪ್ರಯತ್ನಿಸುತ್ತೇವೆ. ಏನು ಭೌತಿಕ ಬದಲಾವಣೆಯಾಗಿದೆ ಎಂಬುದನ್ನು ನಮ್ಮ ಏಕಮಾತ್ರ ವಿವೇಚನೆಯಿಂದ ನಿರ್ಧರಿಸಲಾಗುತ್ತದೆ.',
    'terms.section8.text2': 'ಆ ಪರಿಷ್ಕರಣೆಗಳು ಜಾರಿಗೆ ಬಂದ ನಂತರ ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸುವುದನ್ನು ಅಥವಾ ಬಳಸುವುದನ್ನು ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ಪರಿಷ್ಕೃತ ನಿಯಮಗಳಿಗೆ ಬದ್ಧರಾಗಿರಲು ಒಪ್ಪುತ್ತೀರಿ. ನೀವು ಹೊಸ ನಿಯಮಗಳನ್ನು ಒಪ್ಪದಿದ್ದರೆ, ದಯವಿಟ್ಟು ಸೇವೆಗಳನ್ನು ಬಳಸುವುದನ್ನು ನಿಲ್ಲಿಸಿ.',
    'terms.section9.title': '9. ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    'terms.section9.text': 'ಈ ನಿಯಮಗಳ ಬಗ್ಗೆ ನಿಮಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳಿದ್ದರೆ, ದಯವಿಟ್ಟು ನಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿನ ಸಂಪರ್ಕ ಫಾರ್ಮ್ ಮೂಲಕ ಅಥವಾ terms@nammakendra.org ಗೆ ಇಮೇಲ್ ಕಳುಹಿಸುವ ಮೂಲಕ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    
    // Privacy Policy Page
    'privacy.title': 'ಗೌಪ್ಯತಾ ನೀತಿ',
    'privacy.lastUpdated': 'ಕೊನೆಯ ನವೀಕರಣ: ಏಪ್ರಿಲ್ 9, 2025',
    'privacy.intro.title': 'ಪರಿಚಯ',
    'privacy.intro.text': 'ನಮ್ಮಕೇಂದ್ರದಲ್ಲಿ, ನಾವು ನಿಮ್ಮ ಗೌಪ್ಯತೆಯನ್ನು ಗೌರವಿಸುತ್ತೇವೆ ಮತ್ತು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ರಕ್ಷಿಸಲು ಬದ್ಧರಾಗಿದ್ದೇವೆ. ಈ ಗೌಪ್ಯತಾ ನೀತಿಯು ನೀವು ನಮ್ಮ ವೆಬ್‌ಸೈಟ್ ಅನ್ನು ಭೇಟಿ ಮಾಡಿದಾಗ ಮತ್ತು ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಬಳಸಿದಾಗ ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ನಾವು ಹೇಗೆ ನೋಡಿಕೊಳ್ಳುತ್ತೇವೆ ಎಂಬುದರ ಬಗ್ಗೆ ನಿಮಗೆ ತಿಳಿಸುತ್ತದೆ, ಮತ್ತು ನಿಮ್ಮ ಗೌಪ್ಯತೆಯ ಹಕ್ಕುಗಳು ಮತ್ತು ಕಾನೂನು ನಿಮ್ಮನ್ನು ಹೇಗೆ ರಕ್ಷಿಸುತ್ತದೆ ಎಂಬುದರ ಬಗ್ಗೆ ತಿಳಿಸುತ್ತದೆ.',
    'privacy.collect.title': 'ನಾವು ಸಂಗ್ರಹಿಸುವ ಮಾಹಿತಿ',
    'privacy.collect.text': 'ನಾವು ನಿಮ್ಮ ಬಗ್ಗೆ ವಿವಿಧ ರೀತಿಯ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಸಂಗ್ರಹಿಸಬಹುದು, ಬಳಸಬಹುದು, ಸಂಗ್ರಹಿಸಬಹುದು ಮತ್ತು ವರ್ಗಾಯಿಸಬಹುದು, ಅದನ್ನು ನಾವು ಈ ಕೆಳಗಿನಂತೆ ಗುಂಪು ಮಾಡಿದ್ದೇವೆ:',
    'privacy.collect.identity': 'ಗುರುತಿನ ಡೇಟಾ: ಮೊದಲ ಹೆಸರು, ಕೊನೆಯ ಹೆಸರು, ಬಳಕೆದಾರರ ಹೆಸರು ಅಥವಾ ಇದೇ ರೀತಿಯ ಗುರುತಿಸುವಿಕೆ ಒಳಗೊಂಡಿರುತ್ತದೆ.',
    'privacy.collect.contact': 'ಸಂಪರ್ಕ ಡೇಟಾ: ಇಮೇಲ್ ವಿಳಾಸ ಮತ್ತು ದೂರವಾಣಿ ಸಂಖ್ಯೆಗಳನ್ನು ಒಳಗೊಂಡಿರುತ್ತದೆ.',
    'privacy.collect.technical': 'ತಾಂತ್ರಿಕ ಡೇಟಾ: ಇಂಟರ್ನೆಟ್ ಪ್ರೋಟೋಕಾಲ್ (IP) ವಿಳಾಸ, ನಿಮ್ಮ ಲಾಗಿನ್ ಡೇಟಾ, ಬ್ರೌಸರ್ ಪ್ರಕಾರ ಮತ್ತು ಆವೃತ್ತಿ, ಸಮಯ ವಲಯ ಸೆಟ್ಟಿಂಗ್ ಮತ್ತು ಸ್ಥಳ, ಬ್ರೌಸರ್ ಪ್ಲಗ್-ಇನ್ ಪ್ರಕಾರಗಳು ಮತ್ತು ಆವೃತ್ತಿಗಳು, ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ ಮತ್ತು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್, ಮತ್ತು ಈ ವೆಬ್‌ಸೈಟ್ ಅನ್ನು ಪ್ರವೇಶಿಸಲು ನೀವು ಬಳಸುವ ಸಾಧನಗಳಲ್ಲಿನ ಇತರ ತಂತ್ರಜ್ಞಾನವನ್ನು ಒಳಗೊಂಡಿರುತ್ತದೆ.',
    'privacy.collect.usage': 'ಬಳಕೆಯ ಡೇಟಾ: ನೀವು ನಮ್ಮ ವೆಬ್‌ಸೈಟ್ ಮತ್ತು ಸೇವೆಗಳನ್ನು ಹೇಗೆ ಬಳಸುತ್ತೀರಿ ಎಂಬುದರ ಬಗ್ಗೆ ಮಾಹಿತಿಯನ್ನು ಒಳಗೊಂಡಿರುತ್ತದೆ.',
    'privacy.collect.content': 'ವಿಷಯ ಡೇಟಾ: ನೀವು ನಮ್ಮ ಸೇವೆಗಳಿಗೆ ಸಲ್ಲಿಸುವ ಸಂದೇಶಗಳು, ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳು ಮತ್ತು ಪ್ರಶ್ನೆಗಳ ವಿಷಯವನ್ನು ಒಳಗೊಂಡಿರುತ್ತದೆ.',
    'privacy.use.title': 'ನಾವು ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಹೇಗೆ ಬಳಸುತ್ತೇವೆ',
    'privacy.use.text': 'ಕಾನೂನು ನಮಗೆ ಅನುಮತಿಸಿದಾಗ ಮಾತ್ರ ನಾವು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಬಳಸುತ್ತೇವೆ. ಹೆಚ್ಚಾಗಿ, ನಾವು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಈ ಕೆಳಗಿನ ಸಂದರ್ಭಗಳಲ್ಲಿ ಬಳಸುತ್ತೇವೆ:',
    'privacy.use.item1': 'ನಿಮಗೆ ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಒದಗಿಸಲು ಮತ್ತು ಸುಧಾರಿಸಲು.',
    'privacy.use.item2': 'ನಿಮ್ಮ ವಿಚಾರಣೆಗಳಿಗೆ ಪ್ರತಿಕ್ರಿಯಿಸಲು ಮತ್ತು ನಿಮ್ಮ ವಿನಂತಿಗಳನ್ನು ಪೂರೈಸಲು.',
    'privacy.use.item3': 'ನಮ್ಮ ನಿಯಮಗಳು, ಷರತ್ತುಗಳು ಮತ್ತು ನೀತಿಗಳಿಗೆ ಬದಲಾವಣೆಗಳಂತಹ ಆಡಳಿತಾತ್ಮಕ ಮಾಹಿತಿಯನ್ನು ನಿಮಗೆ ಕಳುಹಿಸಲು.',
    'privacy.use.item4': 'ನಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಅನುಭವವನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸಲು.',
    'privacy.use.item5': 'ಡೇಟಾ ವಿಶ್ಲೇಷಣೆ, ಆಡಿಟ್‌ಗಳು, ವಂಚನೆ ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ತಡೆಗಟ್ಟುವಿಕೆ, ಹೊಸ ಉತ್ಪನ್ನಗಳನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸುವುದು, ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಹೆಚ್ಚಿಸುವುದು, ಸುಧಾರಿಸುವುದು ಅಥವಾ ಮಾರ್ಪಡಿಸುವುದು ಮುಂತಾದ ನಮ್ಮ ವ್ಯಾಪಾರ ಉದ್ದೇಶಗಳಿಗಾಗಿ.',
    'privacy.security.title': 'ಡೇಟಾ ಭದ್ರತೆ',
    'privacy.security.text': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಆಕಸ್ಮಿಕವಾಗಿ ಕಳೆದುಕೊಳ್ಳುವುದು, ಬಳಸುವುದು, ಅಥವಾ ಅನಧಿಕೃತ ರೀತಿಯಲ್ಲಿ ಪ್ರವೇಶಿಸುವುದು, ಬದಲಾಯಿಸುವುದು ಅಥವಾ ಬಹಿರಂಗಪಡಿಸುವುದನ್ನು ತಡೆಯಲು ನಾವು ಸೂಕ್ತವಾದ ಭದ್ರತಾ ಕ್ರಮಗಳನ್ನು ಜಾರಿಗೆ ತಂದಿದ್ದೇವೆ. ಇದಲ್ಲದೆ, ವ್ಯಾಪಾರದ ಅಗತ್ಯವಿರುವ ನೌಕರರು, ಏಜೆಂಟರು, ಗುತ್ತಿಗೆದಾರರು ಮತ್ತು ಇತರ ಮೂರನೇ ವ್ಯಕ್ತಿಗಳಿಗೆ ಮಾತ್ರ ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಪ್ರವೇಶಿಸಲು ನಾವು ಮಿತಿಗೊಳಿಸುತ್ತೇವೆ.',
    'privacy.rights.title': 'ನಿಮ್ಮ ಹಕ್ಕುಗಳು',
    'privacy.rights.text': 'ಕೆಲವು ಸಂದರ್ಭಗಳಲ್ಲಿ, ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾಕ್ಕೆ ಸಂಬಂಧಿಸಿದಂತೆ ಡೇಟಾ ರಕ್ಷಣೆಯ ಕಾನೂನುಗಳ ಅಡಿಯಲ್ಲಿ ನಿಮಗೆ ಹಕ್ಕುಗಳಿವೆ, ಇದರಲ್ಲಿ ಸೇರಿವೆ:',
    'privacy.rights.item1': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಪ್ರವೇಶಿಸಲು ಕೋರುವ ಹಕ್ಕು.',
    'privacy.rights.item2': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾದ ಸರಿಪಡಿಸುವಿಕೆಯನ್ನು ಕೋರುವ ಹಕ್ಕು.',
    'privacy.rights.item3': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾದ ಅಳಿಸುವಿಕೆಯನ್ನು ಕೋರುವ ಹಕ್ಕು.',
    'privacy.rights.item4': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾದ ಪ್ರಕ್ರಿಯೆಗೆ ವಿರೋಧಿಸುವ ಹಕ್ಕು.',
    'privacy.rights.item5': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾದ ಪ್ರಕ್ರಿಯೆಯ ನಿರ್ಬಂಧವನ್ನು ವಿನಂತಿಸುವ ಹಕ್ಕು.',
    'privacy.rights.item6': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾದ ವರ್ಗಾವಣೆಯನ್ನು ವಿನಂತಿಸುವ ಹಕ್ಕು.',
    'privacy.rights.item7': 'ಸಮ್ಮತಿ ಹಿಂಪಡೆಯುವ ಹಕ್ಕು.',
    'privacy.cookies.title': 'ಕುಕೀಸ್',
    'privacy.cookies.text1': 'ನಮ್ಮ ಸೇವೆಯಲ್ಲಿನ ಚಟುವಟಿಕೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ನಿರ್ದಿಷ್ಟ ಮಾಹಿತಿಯನ್ನು ಹೊಂದಿಸಲು ನಾವು ಕುಕೀಸ್ ಮತ್ತು ಇತರ ಟ್ರ್ಯಾಕಿಂಗ್ ತಂತ್ರಜ್ಞಾನಗಳನ್ನು ಬಳಸುತ್ತೇವೆ. ಕುಕೀಸ್ ಅನ್ನು ನಿರಾಮನಾಮ ಅನನ್ಯ ಗುರುತಿಸುವಿಕೆಯನ್ನು ಒಳಗೊಂಡಿರಬಹುದಾದ ಸಣ್ಣ ಪ್ರಮಾಣದ ಡೇಟಾದೊಂದಿಗೆ ಫೈಲ್‌ಗಳಾಗಿವೆ.',
    'privacy.cookies.text2': 'ನೀವು ನಿಮ್ಮ ಬ್ರೌಸರ್ ಅನ್ನು ಎಲ್ಲಾ ಕುಕೀಗಳನ್ನು ನಿರಾಕರಿಸಲು ಅಥವಾ ಕುಕೀ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ ಎಂದು ಸೂಚಿಸಲು ಸೂಚಿಸಬಹುದು. ಆದಾಗ್ಯೂ, ನೀವು ಕುಕೀಗಳನ್ನು ಸ್ವೀಕರಿಸದಿದ್ದರೆ, ನಮ್ಮ ಸೇವೆಯ ಕೆಲವು ಭಾಗಗಳನ್ನು ಬಳಸಲು ನಿಮಗೆ ಸಾಧ್ಯವಾಗದೇ ಇರಬಹುದು.',
    'privacy.contact.title': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    'privacy.contact.text': 'ಈ ಗೌಪ್ಯತಾ ನೀತಿಯ ಬಗ್ಗೆ ನಿಮಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳಿದ್ದರೆ, ದಯವಿಟ್ಟು ನಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿನ ಸಂಪರ್ಕ ಫಾರ್ಮ್ ಮೂಲಕ ಅಥವಾ privacy@nammakendra.org ಗೆ ಇಮೇಲ್ ಕಳುಹಿಸುವ ಮೂಲಕ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    
    // Language selector
    'language.english': 'English',
    'language.kannada': 'ಕನ್ನಡ',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('english');
  
  // Load language preference from localStorage on initial render
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'english' || savedLanguage === 'kannada')) {
      setLanguage(savedLanguage);
    }
  }, []);
  
  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
    
    // Dispatch a custom event so other components can react to language changes
    const event = new CustomEvent('languageChange', { detail: { language } });
    window.dispatchEvent(event);
  }, [language]);
  
  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  
  const contextValue: LanguageContextType = {
    language,
    setLanguage,
    t
  };
  
  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);